//AboutUs.java 
/* 
* To change this license header, choose License Headers in Project Properties. * To change this template file, choose Tools | Templates 
* and open the template in the editor. 
*/ 
package database2project; 
/** 
* 
* @author qgarn 
*/ 
public class AboutUs extends javax.swing.JFrame { 
 /** 
 * Creates new form AboutUs 
 */ 
public AboutUs() { 
	initComponents(); 
	setLocationRelativeTo(null); 
	setResizable(false); 
 } 
 /** 
 * This method is called from within the constructor to initialize the form.  * WARNING: Do NOT modify this code. The content of this method is always  * regenerated by the Form Editor. 
 */ 
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">  
 private void initComponents() { 
	jPanel1 = new javax.swing.JPanel(); 
	jPanel2 = new javax.swing.JPanel(); 
	jLabel1 = new javax.swing.JLabel(); 
	jPanel3 = new javax.swing.JPanel(); 
	jScrollPane1 = new javax.swing.JScrollPane(); 
	jTextArea1 = new javax.swing.JTextArea(); 
	backbtn = new javax.swing.JButton(); 
	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  setUndecorated(true); 
	jPanel1.setBackground(new java.awt.Color(44, 62, 80)); 
	jPanel2.setBackground(new java.awt.Color(255, 48, 79)); 
	jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N  jLabel1.setText("About Us"); 
	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);  jPanel2.setLayout(jPanel2Layout); 
	jPanel2Layout.setHorizontalGroup( 
  
	jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel2Layout.createSequentialGroup() 
	.addContainerGap(26, Short.MAX_VALUE) 
	.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,  158, javax.swing.GroupLayout.PREFERRED_SIZE)
	.addGap(25, 25, 25)) 
 ); 
 jPanel2Layout.setVerticalGroup( 
  
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  .addGroup(jPanel2Layout.createSequentialGroup() 
 .addContainerGap() 
 .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) 
 .addContainerGap()) 
 ); 
 jPanel3.setBackground(new java.awt.Color(255, 48, 79)); 
 jTextArea1.setColumns(20); 
 jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N  jTextArea1.setForeground(new java.awt.Color(255, 255, 255));  jTextArea1.setRows(5); 
 jTextArea1.setText("Bart Porcincula\nAllan Aguimbag \nQuerubin Arnaldo \nJan  Enriquez\nGenerson Castillo "); 
 jTextArea1.setEnabled(false); 
 jScrollPane1.setViewportView(jTextArea1); 
 javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);  jPanel3.setLayout(jPanel3Layout); 
 jPanel3Layout.setHorizontalGroup( 
  
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
 .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,  325, Short.MAX_VALUE) 
 ); 
 jPanel3Layout.setVerticalGroup(
  
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
 .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,  javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE) 
 ); 
  
backbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("RadioButtonMenuItem. selectionBackground")); 
 backbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bart  Porcincula\\Documents\\NetBeansProjects\\Database2Project\\img\\back.png")); // NOI18N 
 backbtn.setText("Back"); 
 backbtn.addActionListener(new java.awt.event.ActionListener() {  public void actionPerformed(java.awt.event.ActionEvent evt) {  backbtnActionPerformed(evt); 
 } 
 }); 
 javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);  jPanel1.setLayout(jPanel1Layout); 
 jPanel1Layout.setHorizontalGroup( 
  
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  .addGroup(jPanel1Layout.createSequentialGroup() 
 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addGap(0, 0, Short.MAX_VALUE)) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel1Layout.createSequentialGroup() 
 .addGap(0, 75, Short.MAX_VALUE) 
 .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel1Layout.createSequentialGroup()
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,  Short.MAX_VALUE) 
 .addComponent(backbtn) 
 .addContainerGap()) 
 ); 
 jPanel1Layout.setVerticalGroup( 
  
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  .addGroup(jPanel1Layout.createSequentialGroup() 
 .addContainerGap(18, Short.MAX_VALUE) 
 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRE LATED) 
 .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELA TED) 
 .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE,  25, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addGap(8, 8, 8)) 
 ); 
 javax.swing.GroupLayout layout = new  
javax.swing.GroupLayout(getContentPane()); 
 getContentPane().setLayout(layout); 
 layout.setHorizontalGroup( 
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) 
 ); 
 layout.setVerticalGroup( 
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,  javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) 
 ); 
 pack(); 
 }// </editor-fold>  
 private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {   // TODO add your handling code here: 
 dispose(); 
 new MainInterface().setVisible(true); 
 }  
 /** 
 * @param args the command line arguments 
 */ 
 public static void main(String args[]) { 
 /* Set the Nimbus look and feel */ 
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional)  "> 
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and  feel. 
 * For details see  
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html   */ 
 try { 
 for (javax.swing.UIManager.LookAndFeelInfo info :  
javax.swing.UIManager.getInstalledLookAndFeels()) { 
 if ("Nimbus".equals(info.getName())) { 
 javax.swing.UIManager.setLookAndFeel(info.getClassName());  break; 
 }
 } 
 } catch (ClassNotFoundException ex) { 
  
java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex); 
 } catch (InstantiationException ex) { 
  
java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex); 
 } catch (IllegalAccessException ex) { 
  
java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex); 
 } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
  
java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex); 
 } 
 //</editor-fold> 
 //</editor-fold> 
 //</editor-fold> 
 //</editor-fold> 
 /* Create and display the form */ 
 java.awt.EventQueue.invokeLater(new Runnable() { 
 public void run() { 
 new AboutUs().setVisible(true); 
 } 
 }); 
 } 
 // Variables declaration - do not modify  
 private javax.swing.JButton backbtn;
 private javax.swing.JLabel jLabel1; 
 private javax.swing.JPanel jPanel1; 
 private javax.swing.JPanel jPanel2; 
 private javax.swing.JPanel jPanel3; 
 private javax.swing.JScrollPane jScrollPane1; 
 private javax.swing.JTextArea jTextArea1; 
 // End of variables declaration  
} 
