//AdminLogin.java 
/* 
* To change this license header, choose License Headers in Project Properties. * To change this template file, choose Tools | Templates 
* and open the template in the editor. 
*/ 
package database2project; 
import javax.swing.JOptionPane; 
import java.sql.*; 
import static database2project.DBconnect.getConnect; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
/** 
* 
* @author Joanjapoy 
*/
public class AdminLogin extends javax.swing.JFrame { 
 private String[] args; 
 PreparedStatement pst; 
 Connection con; 
 /** 
 * Creates new form StudentLogin 
 */ 
 public AdminLogin() { 
 initComponents(); 
 setLocationRelativeTo(null); 
 } 
 /** 
 * This method is called from within the constructor to initialize the form.  * WARNING: Do NOT modify this code. The content of this method is always  * regenerated by the Form Editor. 
 */ 
 @SuppressWarnings("unchecked") 
 // <editor-fold defaultstate="collapsed" desc="Generated Code">   private void initComponents() { 
 jPanel1 = new javax.swing.JPanel(); 
 jLabel3 = new javax.swing.JLabel(); 
 jLabel5 = new javax.swing.JLabel(); 
 close = new javax.swing.JLabel(); 
 jPanel2 = new javax.swing.JPanel(); 
 btn_login = new javax.swing.JButton();
 btn_back = new javax.swing.JButton(); 
 jPasswordField1 = new javax.swing.JPasswordField(); 
 jTextField2 = new javax.swing.JTextField(); 
 jLabel4 = new javax.swing.JLabel(); 
 jLabel2 = new javax.swing.JLabel(); 
 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  setUndecorated(true); 
 getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());  jPanel1.setBackground(new java.awt.Color(44, 62, 80)); 
 jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N  jLabel3.setForeground(new java.awt.Color(255, 255, 255));  jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);  jLabel3.setText("-"); 
 jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));  jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);  jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {  public void mouseClicked(java.awt.event.MouseEvent evt) {  jLabel3MouseClicked(evt); 
 } 
 }); 
 jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N  jLabel5.setForeground(new java.awt.Color(255, 255, 255));  jLabel5.setText("ADMIN LOGIN"); 
 close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N  close.setForeground(new java.awt.Color(255, 255, 255));
 close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);  close.setText("X"); 
 close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));  close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);  close.addMouseListener(new java.awt.event.MouseAdapter() {  public void mouseClicked(java.awt.event.MouseEvent evt) {  closeMouseClicked(evt); 
 } 
 }); 
 javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);  jPanel1.setLayout(jPanel1Layout); 
 jPanel1Layout.setHorizontalGroup( 
  
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel1Layout.createSequentialGroup() 
 .addContainerGap(422, Short.MAX_VALUE) 
 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,  35, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRE LATED) 
 .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE,  35, javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addGap(27, 27, 27)) 
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align ment.LEADING) 
 .addGroup(jPanel1Layout.createSequentialGroup()  .addGap(34, 34, 34) 
 .addComponent(jLabel5) 
 .addContainerGap(267, Short.MAX_VALUE)))  ); 
 jPanel1Layout.setVerticalGroup(
  
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel1Layout.createSequentialGroup() 
 .addContainerGap(34, Short.MAX_VALUE) 
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout. Alignment.BASELINE) 
 .addComponent(jLabel3) 
 .addComponent(close)) 
 .addGap(22, 22, 22)) 
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align ment.LEADING) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel1Layout.createSequentialGroup() 
 .addContainerGap(39, Short.MAX_VALUE) 
 .addComponent(jLabel5) 
 .addGap(17, 17, 17))) 
 ); 
 getContentPane().add(jPanel1, new  
org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); 
 jPanel2.setBackground(new java.awt.Color(255, 48, 79)); 
 btn_login.setBackground(new java.awt.Color(34, 167, 240)); 
 btn_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N  btn_login.setForeground(new java.awt.Color(255, 255, 255));  btn_login.setText("Login"); 
 btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));  btn_login.addActionListener(new java.awt.event.ActionListener() {  public void actionPerformed(java.awt.event.ActionEvent evt) {  btn_loginActionPerformed(evt); 
 }
 }); 
 btn_back.setBackground(new java.awt.Color(192, 57, 43)); 
 btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N  btn_back.setForeground(new java.awt.Color(255, 255, 255));  btn_back.setText("Cancel"); 
 btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));  btn_back.addActionListener(new java.awt.event.ActionListener() {  public void actionPerformed(java.awt.event.ActionEvent evt) {  btn_backActionPerformed(evt); 
 } 
 }); 
 jTextField2.addActionListener(new java.awt.event.ActionListener() {  public void actionPerformed(java.awt.event.ActionEvent evt) {  jTextField2ActionPerformed(evt); 
 } 
 }); 
 jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N  jLabel4.setForeground(new java.awt.Color(255, 255, 255)); 
 jLabel4.setText("Password:"); 
 jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N  jLabel2.setForeground(new java.awt.Color(255, 255, 255)); 
 jLabel2.setText("Username:"); 
 javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);  jPanel2.setLayout(jPanel2Layout); 
 jPanel2Layout.setHorizontalGroup(
  
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  .addGroup(jPanel2Layout.createSequentialGroup() 
 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout. Alignment.LEADING) 
 .addGroup(jPanel2Layout.createSequentialGroup()  .addGap(61, 61, 61) 
 .addComponent(jLabel4) 
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlace ment.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) 
 .addComponent(jPasswordField1,  
javax.swing.GroupLayout.PREFERRED_SIZE, 303,  
javax.swing.GroupLayout.PREFERRED_SIZE)) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,  jPanel2Layout.createSequentialGroup() 
 .addContainerGap(56, Short.MAX_VALUE) 
 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.Gr oupLayout.Alignment.LEADING) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILIN G, jPanel2Layout.createSequentialGroup() 
 .addComponent(jLabel2) 
.addGap(65, 65, 65) 
 .addComponent(jTextField2,  javax.swing.GroupLayout.PREFERRED_SIZE, 303,  
javax.swing.GroupLayout.PREFERRED_SIZE)) 
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILIN G, jPanel2Layout.createSequentialGroup() 
 .addComponent(btn_login,  
javax.swing.GroupLayout.PREFERRED_SIZE, 84,  
javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addGap(55, 55, 55) 
.addComponent(btn_back,  
javax.swing.GroupLayout.PREFERRED_SIZE, 103,  
javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addGap(111, 111, 111))))) 
 .addGap(18, 18, 18))
 ); 
 jPanel2Layout.setVerticalGroup( 
  
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  .addGroup(jPanel2Layout.createSequentialGroup() 
 .addContainerGap() 
 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout. Alignment.LEADING) 
 .addComponent(jTextField2,  
javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,  javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addComponent(jLabel2)) 
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELA TED, 28, Short.MAX_VALUE) 
 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout. Alignment.BASELINE) 
 .addComponent(jLabel4) 
 .addComponent(jPasswordField1,  
javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,  javax.swing.GroupLayout.PREFERRED_SIZE)) 
 .addGap(33, 33, 33) 
 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout. Alignment.BASELINE) 
 .addComponent(btn_back,  
javax.swing.GroupLayout.PREFERRED_SIZE, 37,  
javax.swing.GroupLayout.PREFERRED_SIZE) 
 .addComponent(btn_login,  
javax.swing.GroupLayout.PREFERRED_SIZE, 37,  
javax.swing.GroupLayout.PREFERRED_SIZE)) 
 .addGap(40, 40, 40)) 
 ); 
 getContentPane().add(jPanel2, new  
org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, -1));
 pack(); 
 }// </editor-fold>  
 private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {   String user = jTextField2.getText(); 
 String pass = jPasswordField1.getText(); 
  
 con = getConnect(); 
 String sql = "Select * from adminLogin where username = ? and password = ?";  try { 
 pst = con.prepareStatement(sql); 
 pst.setString(1,user); 
 pst.setString(2,pass); 
 ResultSet rs = pst.executeQuery(); 
 if(rs.next()){ 
 JOptionPane.showMessageDialog(this,"Login Successful!",  "Success!",JOptionPane.INFORMATION_MESSAGE);  dispose(); 
 new AdminMenu().setVisible(true); 
  
 } 
 else{ 
 JOptionPane.showMessageDialog(this,"Incorrect Login Credentials!",  "Error",JOptionPane.ERROR_MESSAGE);  
 dispose(); 
 new AdminLogin().setVisible(true); 
 } 
 } catch (SQLException ex) { 
 Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null,  ex); 
 }
  
  
 }  
 private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {   new MainInterface().setVisible(true); 
 dispose(); 
 }  
 private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {    
 }  
 private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {   // TODO add your handling code here: 
 this.setState(AdminLogin.ICONIFIED); 
 }  
 private void closeMouseClicked(java.awt.event.MouseEvent evt) {   // TODO add your handling code here: 
 con = getConnect(); 
 String sql = "UPDATE studentInfo SET tag = NULL WHERE tag = 'TAG'";  try { 
 pst = con.prepareStatement(sql); 
 pst.executeUpdate(); 
  
  
 } catch (SQLException ex) { 
 Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null,  ex); 
 }
 System.exit(0); 
 }  
 /** 
 * @param args the command line arguments 
 */ 
 public static void AdminLogin() throws ClassNotFoundException { 
 /* Set the Nimbus look and feel */ 
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional)  "> 
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and  feel. 
 * For details see  
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html  
 */ 
 try { 
 for (javax.swing.UIManager.LookAndFeelInfo info :  
javax.swing.UIManager.getInstalledLookAndFeels()) { 
 if ("Nimbus".equals(info.getName())) { 
 javax.swing.UIManager.setLookAndFeel(info.getClassName());  break; 
 } 
 } 
 } catch (ClassNotFoundException ex) { 
  
java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SE VERE, null, ex); 
 } catch (InstantiationException ex) { 
  
java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SE VERE, null, ex); 
 } catch (IllegalAccessException ex) {
  
java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SE VERE, null, ex); 
 } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
  
java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SE VERE, null, ex); 
 } 
 //</editor-fold> 
 //</editor-fold> 
 //</editor-fold> 
 //</editor-fold> 
 /* Create and display the form */ 
 java.awt.EventQueue.invokeLater(new Runnable() { 
 public void run() { 
 new AdminLogin().setVisible(true); 
 } 
 }); 
 } 
 // Variables declaration - do not modify  
 private javax.swing.JButton btn_back; 
 private javax.swing.JButton btn_login; 
 private javax.swing.JLabel close; 
 private javax.swing.JLabel jLabel2; 
 private javax.swing.JLabel jLabel3; 
 private javax.swing.JLabel jLabel4; 
 private javax.swing.JLabel jLabel5; 
 private javax.swing.JPanel jPanel1; 
 private javax.swing.JPanel jPanel2; 
 private javax.swing.JPasswordField jPasswordField1; 
 private javax.swing.JTextField jTextField2;
 // End of variables declaration  
} 
